import logging
import datetime
from typing import Dict, Any

logger = logging.getLogger(__name__)

class CreditMemoGenerator:
    """
    Generates an automated Credit Memo (Markdown format) summarizing all risk insights.
    """

    def generate_memo(self,
                      company_name: str,
                      loan_id: str,
                      risk_metrics: Dict[str, Any],
                      graph_metrics: Dict[str, Any],
                      explanations: list,
                      trajectory_summary: str = "Stable") -> str:

        date_str = datetime.datetime.now().strftime("%Y-%m-%d")

        pd_val = risk_metrics.get("pd_estimate", 0)
        lgd_val = risk_metrics.get("lgd_estimate", 0)
        el_val = risk_metrics.get("expected_loss_estimate", 0)
        pricing = risk_metrics.get("suggested_interest_rate", 0) * 100

        # Determine risk rating (conceptual)
        rating = "Low Risk"
        if pd_val > 0.05: rating = "Moderate Risk"
        if pd_val > 0.10: rating = "High Risk"

        memo = f"""# Automated Credit Memo: {company_name}

**Date:** {date_str}
**Loan ID:** {loan_id}
**Risk Rating:** {rating}

---

## 1. Executive Summary
The requested loan for **{company_name}** has been analyzed. The model suggests a **Probability of Default (PD) of {pd_val:.2%}** and a **Loss Given Default (LGD) of {lgd_val:.2%}**. The expected loss is estimated at **${el_val:,.2f}**.

Based on the risk profile, the suggested pricing is **{pricing:.2f}%**.

## 2. Risk Metrics & Explanations
The primary drivers for the risk assessment are:

"""
        for expl in explanations:
            memo += f"- {expl.get('text', '')}\n"

        memo += f"""
## 3. Network & Supply Chain Risk
* **Contagion Score:** {graph_metrics.get('contagion_score', 0):.2f} (Susceptibility to network shocks)
* **Supply Chain:** {graph_metrics.get('supply_chain_analysis', {}).get('num_suppliers', 0)} Suppliers, {graph_metrics.get('supply_chain_analysis', {}).get('num_customers', 0)} Customers.
* **Concentration Risk:** {graph_metrics.get('supply_chain_analysis', {}).get('supply_chain_concentration_risk', 0):.2f}

## 4. Forward-Looking Simulation (OSWM)
The One-Shot World Model projection indicates a **{trajectory_summary}** trajectory for the credit health over the next 12 months.

## 5. Recommendation
**Automated Recommendation:** {'Proceed with Caution' if rating == 'High Risk' else 'Approve for Review'}

---
*Generated by AI Risk Engine v1.2*
"""
        return memo
